version: "3.9"
services:
  # Database for local dev deployments
  db-dev:
    profiles: [ dev ]
    image: "postgres:15.4-alpine3.18"
    container_name: "${COMPOSE_PROJECT_NAME}-db-dev"
    hostname: db-dev
    restart: unless-stopped
    environment:
      - POSTGRES_USER=db-dev-user
      - POSTGRES_PASSWORD=db-dev-pass
      - POSTGRES_DB=webapp
    ports:
      - "25432:5432"
    volumes:
      - db-dev-data:/var/lib/postgresql/data

  # Database for automated integrations tests
  db-it:
    profiles: [ it ]
    image: "postgres:15.4-alpine3.18"
    container_name: "${COMPOSE_PROJECT_NAME}-db-it"
    hostname: db-it
    restart: unless-stopped
    environment:
      - POSTGRES_USER=db-it-user
      - POSTGRES_PASSWORD=db-it-pass
      - POSTGRES_DB=webapp
    ports:
      - "35432:5432"
    volumes:
      - db-it-data:/var/lib/postgresql/data

volumes:
  db-dev-data:
  db-it-data: