spring:
  config:
    import:
      - optional:file:./.env-dev[.properties]
      - optional:file:../.env-dev[.properties]
      - optional:file:./.env[.properties]
      - optional:file:../.env[.properties]

  logging:
    group:
      db: 'org.hibernate,org.springframework.data.jpa,org.springframework.jdbc'
    level:
      org:
        springframework:
          security: DEBUG

  datasource:
    url: jdbc:postgresql://localhost:25432/webapp
    username: db-dev-user
    password: db-dev-pass
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      pool-name: 'hikari-pool'

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        tmp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
        hbm2ddl:
          auto: none
        ddl-auto: none
    open-in-view: false
    show-sql: true

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

jwt:
  secret: 3d7c8a1f5b6e2d9a4c7f0b3e6a9d2c5f8b1e4a7d0c3f6b9e2a5d8c1f4b7a0e3
